name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'moviebacklog' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x 

    - name: Install libssl1.1
      run: |
        wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb


    - name: Restore dependencies
      run: dotnet restore
      working-directory: MovieBacklog

    - name: Build
      run: dotnet build --no-restore
      working-directory: MovieBacklog

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: MovieBacklog

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Docker build
  #     run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

  #   # Push the Docker image to Heroku Container Registry
  #   - name: Publish
  #     working-directory: MovieBacklog
  #     run: |
  #       heroku container:push web -a $APP_NAME
  #       heroku container:release web -a $APP_NAME