name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'moviebacklog' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x 

    - name: Restore dependencies
      run: dotnet restore
      working-directory: MovieBacklog/MovieBacklog

    - name: Build
      run: dotnet build --no-restore
      working-directory: MovieBacklog/MovieBacklog

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: MovieBacklog/MovieBacklog

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Docker build
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # Push the Docker image to Heroku Container Registry
    - name: Publish
      working-directory: MovieBacklog/MovieBacklog
      run: |
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME